apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-us-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://github.com/yogaarie/template.git
      path: chart-helm
      targetRevision: HEAD
      helm:
        valueFiles:
        - $values/chart-helm/values.yaml          
    - repoURL: 'https://github.com/yogaarie/template.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true
      selfHeal: true